### ISSUE TITLE
Silly question but how do I get it working?

### ISSUE THREAD

**Issue by soydemadrid** [MiSTer-devel/Amstrad_MiSTer#1]
Hi sorry I must be missing something as I can't get the Amstrad Core to work - does it require the SDRAM as possibly that is why? I haven't set that up yet...

I've installed the latest MISTer release, added the latest Amstrad rbf file to the root of the SD card. Made a folder called "Amstrad" then inside the folder I've put boot.rom (renamed from amstrad.rom) and a few .dsk files.

When I mount a .dsk file from the MISTer menu after launching the Amstrad core nothing happens. The screen just stays black.

Also how do I just load up the normal Amstrad "Blue Screen" so I can type basic commands?

Thanks for any help.

**Comment by sorgelig** [comment]
https://github.com/MiSTer-devel/Main_MiSTer/wiki/SDRAM-Requirement-by-cores
