### ISSUE TITLE
roms configuration 

### ISSUE THREAD

**Issue by jeromelesaux** [MiSTer-devel/Amstrad_MiSTer#10]
I would like to install assembly on the mister such as orgams.
I tried to insert the 4 roms using the mister menu, but it seems not to be dedicated to insert roms which interact themselves.
I also tried to rename the roms with the prefix boot like : 
boot.e0A, boot.e1B, boot.e1E and boot.e1F. 
The core reboots but the roms are not usable. 
What is the best practice, to install roms on this core ?

**Comment by sorgelig** [comment]
try to load them manually. Load boot.e0A last as it's autostarts.

**Comment by sorgelig** [comment]
i've tried to load 2 boot roms:
boot.e01
boot.e02
both loaded and started upon core load.
So i cannot confirm the issue.

Best practice is to use forum. Github is to report issues.

**Comment by jeromelesaux** [comment]
I found my mistake (the amsdos header must be removed before to use rom on mister). 
Sorry, I will not restart. I will ask those kind of questions on a forum.
