### ISSUE TITLE
Sound missing in Boulder Dash

### ISSUE THREAD

**Issue by rockford** [MiSTer-devel/Amstrad_MiSTer#2]
Hi
Thanks for the Amstrad core. It is really nice but I have an issue with a sound missing in Boulder Dash (1) when Rockford is digging (the noise sound). All other sounds are ok, but this has vanished. It takes away the right feeling . I am using the latest amstrad rbf and sound is going through hdmi.

Am I missing something? I have tried stereo mix and changing equaliser settings on sound .
In see a fix 5 months back regarding the noise generator. Perhaps the bug is related to this?

**Comment by Titofff** [comment]
Fixed with last release "Amstrad_20200131".
