### ISSUE TITLE
Main melody missing in Toki

### ISSUE THREAD

**Issue by PhantombrainM** [MiSTer-devel/Amstrad_MiSTer#21]
This new Toki homebrew is amazing to play and was developed for years, check it out: https://amstradggp.com/TOKI-GGP-DOWNLOAD.html

Anyways: It's missing the main melody on MISTer FPGA. Here a vid on real hardware:
https://www.youtube.com/watch?v=LLWm7AFt_pw

**Comment by sorgelig** [comment]
Can you be more specific what is missing? I hear music while playing the game. Looks similar to youtube.

**Comment by PhantombrainM** [comment]
Sure. Since it's hard to explain music, I sang the missing melody for you :) 

https://youtube.com/shorts/l9E1rjBIPDk?feature=share

**Comment by sorgelig** [comment]
lol.. That's the best explanation! :)

But on my MiSTer i hear this melody.. May be there are some settings messed?

**Comment by PhantombrainM** [comment]
After touching all the settings, I could not solve the problem.

But when I unplugged the analogue jack plug, the sound was audible after I plugged it in again and the problem with the missing sound could not be recreated again. So I think it was a mechanical problem. The channel has probably been zeroed out or something.

In any case, I made you laugh and brightened your day! ;)
