### ISSUE TITLE
Missing sound on JET BOOT JACK

### ISSUE THREAD

**Issue by Titofff** [MiSTer-devel/Amstrad_MiSTer#4]
Hello !

Same problem as boulderdash missing sound when jack move.

**Comment by gyurco** [comment]
Maybe this one:
https://github.com/gyurco/MiSTery/commit/e5556cc2cb4e8f37d18dda0f1386fdc5561a4118
Helped on Atari ST with some missing sounds (tone_gen_op[i] <= ~ymreg[7][i]; is the relevant part)

**Comment by sorgelig** [comment]
@gyurco 
thanks! i will check that.
I think using BRAM for simple volume mixing is too exaggerated ;)

**Comment by sorgelig** [comment]
Yep, that line fixes the sound.

**Comment by gyurco** [comment]
The problem is that the "mixing" on Atari ST is just short-circuiting the three output channels, and the output is not a linear function of the 3 values. For playing back PCM sound (very common on the ST), it's mandatory to simulate the original output, otherwise the result is too noisy and/or distorted.

**Comment by gyurco** [comment]
Btw, I've did some improvements in the MiST version:
https://github.com/gyurco/Amstrad_MiST/commits/master
Then I discovered that the GA already decapped & reverse engineered, so probably I'll work on it a bit more.

**Comment by sorgelig** [comment]
CRTC improvements would be more beneficial.

**Comment by gyurco** [comment]
- most problems I saw were not CRTC problems
- the GA was decapped, not the CRTC :)
- maybe after that, I'll look into the remaining CRTC issues, too

**Comment by Titofff** [comment]
Fixed with last release "Amstrad_20200131".

Thanks a lot ! sounds ok now for Boulder Dash & Jet Boot Jack et some others probably.
