### ISSUE TITLE
Voice sample missing in Flyspy

### ISSUE THREAD

**Issue by iondrive2020** [MiSTer-devel/Amstrad_MiSTer#7]
As soon as the game 'Fly Spy by Mastertronic' loads, it should a speech sample that says "Welcome to Fly Spy" but instead it is silent on the Amstrad Mister Core.

Version: v200131 tried CRTC 1 & 2

**Comment by Titofff** [comment]
Now with Last update, digital voices work fine ;)

**Comment by sorgelig** [comment]
good

**Comment by iondrive2020** [comment]
Excellent
